import MainProvider from "@/components/providers/MainProvider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Shopify App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log("layout");
  console.log(
    "process.env.CONFIG_SHOPIFY_API_KEY",
    process.env.CONFIG_SHOPIFY_API_KEY
  );
  return (
    <html lang="en">
      <head>
        {/* <script>var global = global || window;</script> */}
        <script
          src={`https://cdn.shopify.com/shopifycloud/app-bridge.js?apiKey=${process.env.CONFIG_SHOPIFY_API_KEY}`}
        ></script>
      </head>
      <body className={inter.className}>
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
